test for new 1.9 kernel

diff --git a/artifacts/arm-trusted-firmware/rk3588/pkg.yaml b/artifacts/arm-trusted-firmware/rk3588/pkg.yaml
--- a/artifacts/arm-trusted-firmware/rk3588/pkg.yaml
+++ b/artifacts/arm-trusted-firmware/rk3588/pkg.yaml
@@ -19,19 +19,22 @@ steps:
         tar xzf arm-trusted-firmware.tar.gz --strip-components=1
 
         # https://review.trustedfirmware.org/c/TF-A/trusted-firmware-a/+/21840/6 and related chain
-        for patch in $(find /pkg/patches -type f -name "*.patch" | sort); do
-          patch -p1 < $patch || (echo "Failed to apply patch $patch" && exit 1)
-        done
+        #for patch in $(find /pkg/patches -type f -name "*.patch" | sort); do
+        #  patch -p1 < $patch || (echo "Failed to apply patch $patch" && exit 1)
+        #done
     # rk3588
     build:
       - |
+        # https://github.com/ARM-software/arm-trusted-firmware/blob/master/docs/getting_started/initial-build.rst
+        export CROSS_COMPILE=/toolchain/bin/aarch64-linux-musl-
+
         make realclean
         mkdir -p $(pwd)/build/rk3588/release/
 
         # https://salsa.debian.org/debian/arm-trusted-firmware/-/commit/6424a59e08585af7f8a56f1e16ecc6a6b9e4ad7a
         # https://salsa.debian.org/debian/arm-trusted-firmware/-/commit/6ed8f61df3b07bb22a68a0fc189ec3b3f7b00dbd
         # https://developer.trustedfirmware.org/T996
-        TF_LDFLAGS=--no-warn-rwx-segments CFLAGS=--param=min-pagesize=0 make -j $(nproc) PLAT=rk3588 DEBUG=0 bl31
+        CFLAGS=--param=min-pagesize=0 make -j $(nproc) PLAT=rk3588 DEBUG=0 bl31
     install:
       - |
         mkdir -p /rootfs/arm-trusted-firmware/rk3588
